### ISSUE TITLE
NoMethodError: undefined method `policy' for ViewHelper Test Unit

### ISSUE THREAD

**Issue by gkulasik** [elabs/pundit#301]
Hi,

I am having an issue with testing my views. I created a couple of view helpers and use pundit to decide if they should be authorized to view certain content in the helper. The helpers all work fine in development. But in my tests they are failing with the message (for example):

    AnswersHelperTest#test_answer_input_text_helper:
    NoMethodError: undefined method `policy' for #<AnswersHelperTest:0x00000006076998>
       app/helpers/answers_helper.rb:13:in `answer_input_text_helper'
       test/helpers/answers_helper_test.rb:16:in `block in <class:AnswersHelperTest>'

I have tried including anything and everything I could in my test_helper.rb or in the test files themselves but it either fails to pick it up or some other error occurs. I have tried including Pundit in ActionView::TestCase and requiring Pundit. 

Any help you can provide would be appreciated. Thank you.

Edit:
I wrote a couple more tests and it seems this issue is for all tests because this same error came up in model tests.

Greg

**Comment by gkulasik** [comment]
I think I have figured this issue out. 

Need to add to test_helper.rb:
```
class ActiveSupport::TestCase
    include Pundit
```
This resulted in issues still because I was calling policy(object) (as I want the method to work regardless  of the object). In some tests I can call _____Policy because I know the type I am using but I cannot always. The issue came from missing the user. 

I use Devise and I added this outside of class ActiveSupport::TestCase:
```
class ActionView::TestCase
  def current_user
    users(:correct)
  end
end
```
This helped my use current_user in my views to test my helpers which use some policies.
