### ISSUE TITLE
Is authorize accidentally deleting my association?

### ISSUE THREAD

**Issue by daneelliotthamilton** [elabs/pundit#314]
I've been developing an application which allows users for follow matters. The application creates a following, which is essentially a join table for users and matters. I created at policy that only allows admins to remove followers, but a current user can unfollow the matter. However when I clicked on the link via a remote request with a general account (should have returned unauthorised), it allow the following to be destroyed and it also destroys the associated matter object. When i comment out the authorize method in my following controller, it deletes the following but the matter object remains. Is authorize deleting my association?

My followingcontroller:
````
class FollowingsController < ApplicationController
  before_action :set_following, only: [:show, :edit, :update, :destroy]
  before_action :set_matter, only: [:new, :create]


  def new
    @following = @matter.followings.new
    respond_to do |format|
      format.js
    end
  end

  def create

    @following = @matter.followings.new(following_params)
    @following.current_user = current_user

    respond_to do |format|
      if @following.save
        format.html { redirect_to @following, notice: 'Following was successfully created.' }
        format.json { render :show, status: :created, location: @following }
        format.js
      else
        format.html { render :new }
        format.json { render json: @following.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    authorize @following
    @following.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Following.find(params[:id])
    end

    def set_matter
      @matter = Matter.find(params[:matter_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following).permit(:matter_id, :user_id, :type)
    end
end
````
my following policy:
````
class FollowingPolicy
  attr_reader :user, :following

  def initialize(user, following)
    @user = user
    @following = following
  end

  def destroy?
    user.admin? or following.user.id == user.id
  end
end
````
followings/destroy.js.erb
````
$('following-<%= @following.id %>').fadeOut('slow', function(){
	this.remove();
});
````
My stack trace:
````
Started DELETE "/followings/24" for 127.0.0.1 at 2015-09-09 13:29:10 -0400
Processing by FollowingsController#destroy as JS
  Parameters: {"id"=>"24"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 7]]
  Organisation Load (0.2ms)  SELECT  "organisations".* FROM "organisations" WHERE "organisations"."id" = $1 LIMIT 1  [["id", 5]]
  Organisation Load (0.2ms)  SELECT  "organisations".* FROM "organisations" WHERE "organisations"."subdomain" = $1 LIMIT 1  [["subdomain", "sjco"]]
  Organisation Load (0.3ms)  SELECT  "organisations".* FROM "organisations" WHERE "organisations"."subdomain" = $1  ORDER BY "organisations"."id" ASC LIMIT 1  [["subdomain", "sjco"]]
  Following Load (0.3ms)  SELECT  "followings".* FROM "followings" WHERE "followings"."organisation_id" = $1 AND "followings"."id" = $2 LIMIT 1  [["organisation_id", 5], ["id", 24]]
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."organisation_id" = $1 AND "users"."id" = $2 LIMIT 1  [["organisation_id", 5], ["id", 6]]
Redirected to http://sjco.gestusapp.dev/matters/1
Completed 302 Found in 43ms (ActiveRecord: 2.0ms)


Started DELETE "/matters/1" for 127.0.0.1 at 2015-09-09 13:29:10 -0400
Processing by MattersController#destroy as JS
  Parameters: {"id"=>"1"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 7]]
  Organisation Load (0.3ms)  SELECT  "organisations".* FROM "organisations" WHERE "organisations"."id" = $1 LIMIT 1  [["id", 5]]
  Organisation Load (0.2ms)  SELECT  "organisations".* FROM "organisations" WHERE "organisations"."subdomain" = $1 LIMIT 1  [["subdomain", "sjco"]]
  Organisation Load (0.4ms)  SELECT  "organisations".* FROM "organisations" WHERE "organisations"."subdomain" = $1  ORDER BY "organisations"."id" ASC LIMIT 1  [["subdomain", "sjco"]]
  Matter Load (0.4ms)  SELECT  "matters".* FROM "matters" WHERE "matters"."organisation_id" = $1 AND "matters"."id" = $2 LIMIT 1  [["organisation_id", 5], ["id", 1]]
   (0.3ms)  BEGIN
  Task Load (0.4ms)  SELECT "tasks".* FROM "tasks" WHERE "tasks"."organisation_id" = $1 AND "tasks"."matter_id" = $2  [["organisation_id", 5], ["matter_id", 1]]
  Document Load (0.2ms)  SELECT "documents".* FROM "documents" WHERE "documents"."organisation_id" = $1 AND "documents"."matter_id" = $2  [["organisation_id", 5], ["matter_id", 1]]
  BundleItem Load (0.2ms)  SELECT "bundle_items".* FROM "bundle_items" WHERE "bundle_items"."organisation_id" = $1 AND "bundle_items"."matter_id" = $2  [["organisation_id", 5], ["matter_id", 1]]
  Note Load (0.6ms)  SELECT "notes".* FROM "notes" WHERE "notes"."organisation_id" = $1 AND "notes"."matter_id" = $2  [["organisation_id", 5], ["matter_id", 1]]
  Hour Load (2.9ms)  SELECT "hours".* FROM "hours" WHERE "hours"."organisation_id" = $1 AND "hours"."recordable_id" = $2 AND "hours"."recordable_type" = $3  [["organisation_id", 5], ["recordable_id", 25], ["recordable_type", "Note"]]
  SQL (0.9ms)  DELETE FROM "hours" WHERE "hours"."id" = $1  [["id", 5]]
  Comment Load (0.6ms)  SELECT "comments".* FROM "comments" WHERE "comments"."organisation_id" = $1 AND "comments"."commentable_id" = $2 AND "comments"."commentable_type" = $3  [["organisation_id", 5], ["commentable_id", 25], ["commentable_type", "Note"]]
  SQL (0.4ms)  DELETE FROM "notes" WHERE "notes"."id" = $1  [["id", 25]]
  SQL (0.4ms)  UPDATE "matters" SET "updated_at" = '2015-09-09 17:29:10.177558' WHERE "matters"."id" = $1  [["id", 1]]
  Hour Load (0.4ms)  SELECT "hours".* FROM "hours" WHERE "hours"."organisation_id" = $1 AND "hours"."recordable_id" = $2 AND "hours"."recordable_type" = $3  [["organisation_id", 5], ["recordable_id", 52], ["recordable_type", "Note"]]
  Comment Load (0.4ms)  SELECT "comments".* FROM "comments" WHERE "comments"."organisation_id" = $1 AND "comments"."commentable_id" = $2 AND "comments"."commentable_type" = $3  [["organisation_id", 5], ["commentable_id", 52], ["commentable_type", "Note"]]
  SQL (0.3ms)  DELETE FROM "notes" WHERE "notes"."id" = $1  [["id", 52]]
  SQL (0.4ms)  UPDATE "matters" SET "updated_at" = '2015-09-09 17:29:10.184528' WHERE "matters"."id" = $1  [["id", 1]]
  Hour Load (0.4ms)  SELECT "hours".* FROM "hours" WHERE "hours"."organisation_id" = $1 AND "hours"."matter_id" = $2  [["organisation_id", 5], ["matter_id", 1]]
  Following Load (0.3ms)  SELECT "followings".* FROM "followings" WHERE "followings"."organisation_id" = $1 AND "followings"."matter_id" = $2  [["organisation_id", 5], ["matter_id", 1]]
  PublicActivity::Activity Load (1.0ms)  SELECT "activities".* FROM "activities" WHERE "activities"."organisation_id" = $1 AND "activities"."trackable_id" = $2 AND "activities"."trackable_type" = $3  [["organisation_id", 5], ["trackable_id", 22], ["trackable_type", "Following"]]
  SQL (0.4ms)  DELETE FROM "activities" WHERE "activities"."id" = $1  [["id", 151]]
  SQL (0.3ms)  DELETE FROM "followings" WHERE "followings"."id" = $1  [["id", 22]]
  SQL (0.3ms)  UPDATE "matters" SET "updated_at" = '2015-09-09 17:29:10.194491' WHERE "matters"."id" = $1  [["id", 1]]
  PublicActivity::Activity Load (0.3ms)  SELECT "activities".* FROM "activities" WHERE "activities"."organisation_id" = $1 AND "activities"."trackable_id" = $2 AND "activities"."trackable_type" = $3  [["organisation_id", 5], ["trackable_id", 24], ["trackable_type", "Following"]]
  SQL (0.2ms)  DELETE FROM "activities" WHERE "activities"."id" = $1  [["id", 153]]
  SQL (0.2ms)  DELETE FROM "followings" WHERE "followings"."id" = $1  [["id", 24]]
  SQL (0.4ms)  UPDATE "matters" SET "updated_at" = '2015-09-09 17:29:10.199280' WHERE "matters"."id" = $1  [["id", 1]]
  Party Load (0.2ms)  SELECT "parties".* FROM "parties" WHERE "parties"."organisation_id" = $1 AND "parties"."matter_id" = $2  [["organisation_id", 5], ["matter_id", 1]]
  Engagement Load (0.4ms)  SELECT "engagements".* FROM "engagements" WHERE "engagements"."organisation_id" = $1 AND "engagements"."engageable_id" = $2 AND "engagements"."engageable_type" = $3  [["organisation_id", 5], ["engageable_id", 1], ["engageable_type", "Matter"]]
  SQL (0.3ms)  DELETE FROM "engagements_users" WHERE "engagements_users"."engagement_id" = $1  [["engagement_id", 25]]
  SQL (0.9ms)  DELETE FROM "engagements" WHERE "engagements"."type" IN ('CourtDate') AND "engagements"."id" = $1  [["id", 25]]
  Matter Load (0.3ms)  SELECT  "matters".* FROM "matters" WHERE "matters"."organisation_id" = $1 AND "matters"."id" = $2 LIMIT 1  [["organisation_id", 5], ["id", 1]]
  SQL (0.4ms)  UPDATE "matters" SET "updated_at" = '2015-09-09 17:29:10.223735' WHERE "matters"."id" = $1  [["id", 1]]
  SQL (0.5ms)  INSERT INTO "activities" ("organisation_id", "key", "owner_id", "owner_type", "trackable_id", "trackable_type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["organisation_id", 5], ["key", "matter.destroy"], ["owner_id", 7], ["owner_type", "User"], ["trackable_id", 1], ["trackable_type", "Matter"], ["created_at", "2015-09-09 17:29:10.228309"], ["updated_at", "2015-09-09 17:29:10.228309"]]
  SQL (1.8ms)  DELETE FROM "matters" WHERE "matters"."id" = $1  [["id", 1]]
   (0.8ms)  COMMIT
Redirected to http://sjco.gestusapp.dev/matters
Completed 302 Found in 130ms (ActiveRecord: 21.8ms)


Started DELETE "/matters" for 127.0.0.1 at 2015-09-09 13:29:10 -0400

ActionController::RoutingError (No route matches [DELETE] "/matters"):
  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/application.rb:164:in `call'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:155:in `handle'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:109:in `rescue in block (2 levels) in start'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:106:in `block (2 levels) in start'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `each'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `start'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
  /Users/daneelliott-hamilton/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'


  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.8ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/routing_error.text.erb (31.9ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.6ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (1.3ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.6ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (107.9ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.5ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.6ms)
  Rendered /Users/daneelliott-hamilton/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (211.9ms)
````
I have no callbacks in my following model.
Using Rails 4.2.2, Pundit 1.0.1 on Mac OS X 10.10.5

**Comment by jnicklas** [comment]
The easiest way to find out is to read the code. It's here https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L112-L123

You can see that it does not in fact delete anything ;)

I don't know what's going on, seems like you're going to have to debug this one a bit to figure out what's going on.

**Comment by daneelliotthamilton** [comment]
Yea I looked at the source. But its very strange since it does not delete my association when I removed the authorize method from the controller.

**Comment by daneelliotthamilton** [comment]
When I include the authorize method it redirects to my matters controller.

**Comment by ce07c3** [comment]
Like @jnicklas stated, the error is with prob. 1 not in Pundit's code. Check your models, maybe there's a `dependent: :destroy` declaration.

**Comment by vanboom** [comment]
I think the issue is related to using AJAX for the delete action...

Click Delete (AJAX) -> Pundit denies authorization -> redirect to root_path --> *!@#! something else gets deleted

I haven't tracked this down all of the way yet, but I suggest forcing destroy? to return false, and testing your AJAX based delete links to make sure you are handling the delete policy properly.
