### ISSUE TITLE
record model object is nil in rspec

### ISSUE THREAD

**Issue by dgoradia** [elabs/pundit#337]
I have a user_policy like:
```ruby
  def show?
    user.has_role?(:super) or (user.has_role?(:admin) and record.role_id >= user.role_id) or (user.id == record.id)
  end
```

And a user_policy_spec:
```ruby
...

  let(:user) { User.new }

  subject { described_class }

  permissions :show? do
    it 'grants super user to show any user' do
      expect(subject).to permit(User.new(role_id: role('super').id))
    end

    it 'grants admin user to show lesser roles and self' do
      expect(subject).to permit(User.new(role_id: role('admin').id))
    end
  end

...

private
def role(role)
  role = Role.find_by_name(role)
end
```

My rspec fails with
```ruby
Failures:

  1) UserPolicy show? grants admin user to show lesser roles and self
     Failure/Error: expect(subject).to permit(User.new(role_id: role('admin').id))
     NoMethodError:
       undefined method `role_id' for nil:NilClass
     # ./app/policies/user_policy.rb:9:in `show?'
     # ./spec/policies/user_policy_spec.rb:15:in `block (3 levels) in <top (required)>'
```
It looks like record (the model object in question) is returning nil. Is there a different way to write this?

**Comment by vemv** [comment]
I doubt somebody will debug your issue for you!

You should use a debugger (like Pry) and realise the exact line of code at fault. If it turns out to be Pundit's fault, create a reproducible case instead of pasting your project's code.

Cheers - Victor

**Comment by jnicklas** [comment]
I agree with @vemv ;)
