### ISSUE TITLE
Pundit::NotDefinedError - unable to find scope

### ISSUE THREAD

**Issue by phlegx** [elabs/pundit#429]
Hi!

I use gem version **1.1.0** and I get the following error:

```
Pundit::NotDefinedError - unable to find scope `UserPolicy::Scope` for `User(id: integer, ...
  pundit (1.1.0) lib/pundit/policy_finder.rb:51:in `scope!'
  pundit (1.1.0) lib/pundit.rb:90:in `policy_scope!'
  pundit (1.1.0) lib/pundit.rb:284:in `pundit_policy_scope'
  pundit (1.1.0) lib/pundit.rb:226:in `policy_scope'
```

I have a file `user_policy.rb` in `app/policies`:

```ruby
class UserPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope.all
    end
  end
end
```

My application controller has `include Pundit`. In my controller I call:

```ruby
def index
  policy_scope(User)
end
```
**Any idea where is the problem?**

**Comment by phlegx** [comment]
**Solved!** :laughing: I have forgot to initialize the class `Scope` in the `ApplicationPolicy`. OK I need a break! :coffee: 

```ruby
class ApplicationPolicy
  attr_reader :user, :record

  def initialize(user, record)
    @user = user
    @record = record
  end

  class Scope
    attr_reader :user, :scope

    def initialize(user, scope)
      @user = user
      @scope = scope
    end

    def resolve
      scope
    end
  end

  ...
end
```
